import { Zap, BookOpen, FileSpreadsheet } from 'lucide-react';
import type { PricingPlan } from './types';

export const pricingPlans: PricingPlan[] = [
  {
    name: 'Plan Autodidacta',
    icon: FileSpreadsheet,
    price: '79',
    description: 'Sin clases ni soporte. Recibes los recursos y operas completamente por tu cuenta.',
    features: [
      'Excel de seguimiento de apuestas (el mismo que usan nuestros alumnos)',
      'Calculadora de calculo de value bets y EV esperado',
      'Calculadora de stake y gestion de bankroll',
      'Lista de casas de apuestas recomendadas y cuales evitar',
      'Lista de herramientas y escaneres de cuotas que debes usar',
      '❌ Sin clases ni formacion',
      '❌ Sin soporte ni ayuda personalizada',
      '❌ Trabajas completamente solo',
    ],
    highlighted: false,
    recommended: false,
  },
  {
    name: 'Plan Activo',
    icon: BookOpen,
    price: '197',
    description: 'Aprende nuestra metodologia de inversion en apuestas deportivas.',
    features: [
      '+ Todo lo incluido en Autodidacta',
      '10 horas de contenido formativo (videos + materiales)',
      '2 clases online en directo para dudas y cuestiones',
      'Acceso a todas las guias y materiales del curso',
    ],
    content: [
      'Fundamentos del Matched Betting desde cero',
      'Como identificar y aprovechar los bonos de bienvenida',
      'Matched betting con apuestas free bet y reembolsos',
      'Value Betting: que es y como detectar cuotas con valor',
      'Como calcular el EV (valor esperado) de una apuesta',
      'Que casas de apuestas usar y cuales evitar',
      'Mejores herramientas y escaneres de cuotas del mercado',
      'Gestion de bankroll y control de varianza',
      'Estrategia de apuestas a largo plazo',
      'Errores mas comunes y como evitarlos',
    ],
    highlighted: false,
    recommended: true,
  },
  {
    name: 'Plan Profesional',
    icon: Zap,
    price: '297',
    description: 'Dominio avanzado de Value Betting, Trading Deportivo y nuevas tecnicas. Para quien quiere llevar las apuestas al siguiente nivel.',
    features: [
      '+ Todo lo incluido en Metodologia Activa',
      '20 horas de contenido avanzado (videos + materiales)',
      '4 clases online en directo para dudas y casos reales',
      'Apuesta con nosotros en directo cada semana',
    ],
    content: [
      '— VALUE BETTING AVANZADO —',
      'Modelo matematico de deteccion de value bets',
      'Como construir tu propio modelo de probabilidades',
      'Comparacion de cuotas entre bookmakers: herramientas profesionales',
      'Analisis de mercados liquidos vs iliquidos',
      'Gestion de stakes segun Kelly Criterion',
      'Control de varianza y drawdown a largo plazo',
      'Como leer el movimiento de lineas y que senala',
      'Seguimiento y analisis de resultados con estadistica real',
      '— TRADING DEPORTIVO —',
      'Que es el trading deportivo y en que se diferencia del betting',
      'Plataformas de trading: Betfair, Smarkets y como usarlas',
      'Estrategias de trading en mercados pre-partido',
      'Trading en directo (in-play): oportunidades y riesgos',
      'Scalping y swing trading en apuestas deportivas',
      'Gestion de posiciones abiertas y como cerrar con beneficio',
      '— NUEVAS TECNICAS —',
      'Arbitraje deportivo: como detectar y ejecutar arbs',
      'Bonus abuse avanzado y tecnicas de reload',
      'Apuestas a mercados alternativos de alto valor',
      'Automatizacion y uso de bots de forma legal',
      'Construccion de un sistema de apuestas sostenible',
    ],
    highlighted: true,
    recommended: false,
  },
];
