import { Zap, BookOpen, FileSpreadsheet } from 'lucide-react';
import type { PricingPlan } from './types';

export const pricingPlans: PricingPlan[] = [
  {
    name: 'El Método, por capas',
    icon: FileSpreadsheet,
    price: '1',
    description: 'Es el mismo contenido base de El Método, pero desbloqueado por niveles de pago progresivo y no lineal.',
    features: [
      'Empiezas por 1 EUR y accedes al primer nivel del contenido',
      'Cada nivel desbloquea una parte nueva del mismo método principal',
      'No es lineal: puedes elegir que información desbloquear primero',
      'Pagas sólo los bloques que quieras abrir en cada momento',
      'Ideal si prefieres avanzar poco a poco en lugar de pagar todo de golpe',
      'La ruta completa es la misma, solo cambia el formato de pago por capas',
      '❌ No se desbloquea todo el curso desde el inicio',
      '❌ Debes completar cada pago para pasar al siguiente nivel',
    ],
    highlighted: false,
    recommended: false,
  },
  {
    name: 'El Método.',
    icon: BookOpen,
    price: '197',
    description: 'Aprende nuestra metodología de inversión en apuestas deportivas.',
    features: [
      '+ Todo lo incluido en El Método por capas',
      '10 horas de contenido formativo (videos + materiales)',
      '2 clases online en directo para dudas y cuestiones',
      'Acceso a todas las guías y materiales del curso',
    ],
    content: [
      'Fundamentos del Matched Betting desde cero',
      'Cómo identificar y aprovechar los bonos de bienvenida',
      'Matched betting con apuestas freebets y reembolsos',
      'Value Betting: qué es y cómo detectar cuotas con valor',
      'Cómo calcular el EV (valor esperado) de una apuesta',
      'Qué casas de apuestas usar y cuáles evitar',
      'Mejores herramientas y escaneres de cuotas del mercado',
      'Gestión de bankroll y control de varianza',
      'Estrategia de apuestas a largo plazo',
      'Errores más comunes y cómo evitarlos',
    ],
    highlighted: true,
    recommended: false,
  },
  {
    name: 'El Método, plus',
    icon: Zap,
    price: 'Bajo demanda',
    description: 'Aplicamos El Método en tus cuentas de casas de apuestas usando mi capital y un reparto porcentual del beneficio.',
    features: [
      'Servicio personalizado bajo demanda',
      'Aplicamos El Método directamente en tus cuentas de casas de apuestas',
      'Operativa con mi dinero para ejecutar la estrategia',
      'Tu beneficio es porcentual y siempre depende de las ganancias reales',
      'Sólo cobramos cuando hay beneficio',
    ],
    content: [
      'Evaluación inicial de tus cuentas y límites disponibles',
      'Definición del marco de riesgo y objetivos de beneficio',
      'Ejecución de operativa por nuestra parte con capital propio',
      'Seguimiento de resultados con registro transparente',
      'Liquidación por porcentaje exclusivamente sobre ganancias',
    ],
    highlighted: false,
    recommended: true,
  },
];
